### ISSUE TITLE
Install ?

### ISSUE THREAD

**Issue by RudySixOw** [plewin/tp-link-modem-router#16]
Hello, sorry for my deplorable English.
I must not be good, I have cloned the git, installed nodejs and yarn, on the other hand I do not see an install file and when I run yarn install it says to me: "00h00m00s 0/0:: ERROR: [Errno 2] No such file or directory: 'install' ".
Would I have missed a step, do I have to go through docker?

Thanks in advance.

**Comment by plewin** [comment]
Hey,
Are you on Ubuntu? It seems it's a common problem on Ubuntu and the yarn
called is not the yarn that's needed. It's a different yarn that is already
installed
You need node and yarn for node.

Best regards,

**Comment by RudySixOw** [comment]
Thank you for your reply.
Indeed I am on a debian. So I uninstalled the yarn from apt source and install via npm and it works.
A big thank-you.
