### ISSUE TITLE
IP Refreshing

### ISSUE THREAD

**Issue by sukhcha-in** [plewin/tp-link-modem-router#22]
First of all thanks for all the hard work you've done with this project.
I'm trying to turn off mobile data then turning it on again, so ISP assigns me new IP address.

<img src="https://i.imgur.com/emW7f2o.png"/>

In network tab request goes to `cgi_gdpr` path with payload of `data` and `sign`, and some other headers which are already used in this project to send SMS.

Now how can I decrypt the `data` from payload so I can know what payload is actually being sent?

Thanks again.

**Comment by plewin** [comment]
Hello,

In the project Readme at the section "development and debugging the
router's protocol" I left a code snippet you can paste in the Console tab
of your browser.
Paste it in your console tab and the decrypted protocol with appear in
Console and not the Network tab.

Kind regards,

**Comment by sukhcha-in** [comment]
@plewin thank you so much :)

**Comment by amen160** [comment]
Hi, @sukhcha-in @plewin  can you share me code to "Turn off mobile data then turn on again"? Please help me.

**Comment by sukhcha-in** [comment]
@amen160 Login into the router's UI, open developer options on the browser and run this code in the console.
Turn off data and you can see requests. You can easily replicate them afterwards programmatically.
```
$.Iencryptor.AESDecrypt_backup = $.Iencryptor.AESDecrypt;
$.Iencryptor.AESEncrypt_backup = $.Iencryptor.AESEncrypt;
$.Iencryptor.AESDecrypt = function(data) {
	let decrypted = $.Iencryptor.AESDecrypt_backup(data);
	console.log("RECV:\n" + decrypted);
	return decrypted;
}
$.Iencryptor.AESEncrypt = function(data) {
	console.log("SEND:\n" + data);
	return $.Iencryptor.AESEncrypt_backup(data);
}
```
